[2025-03-09T19:21:00.976+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-09T19:21:01.044+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: a1.insert_data_to_mongodb scheduled__2025-03-08T00:00:00+00:00 [queued]>
[2025-03-09T19:21:01.057+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: a1.insert_data_to_mongodb scheduled__2025-03-08T00:00:00+00:00 [queued]>
[2025-03-09T19:21:01.058+0000] {taskinstance.py:2867} INFO - Starting attempt 30 of 31
[2025-03-09T19:21:01.068+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): insert_data_to_mongodb> on 2025-03-08 00:00:00+00:00
[2025-03-09T19:21:01.084+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=145) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-09T19:21:01.086+0000] {standard_task_runner.py:72} INFO - Started process 146 to run task
[2025-03-09T19:21:01.088+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'a1', 'insert_data_to_mongodb', 'scheduled__2025-03-08T00:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmptxtdmz5u']
[2025-03-09T19:21:01.090+0000] {standard_task_runner.py:105} INFO - Job 49: Subtask insert_data_to_mongodb
[2025-03-09T19:21:01.131+0000] {task_command.py:467} INFO - Running <TaskInstance: a1.insert_data_to_mongodb scheduled__2025-03-08T00:00:00+00:00 [running]> on host e261c4a55bbc
[2025-03-09T19:21:01.591+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='example@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='a1' AIRFLOW_CTX_TASK_ID='insert_data_to_mongodb' AIRFLOW_CTX_EXECUTION_DATE='2025-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='30' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-08T00:00:00+00:00'
[2025-03-09T19:21:01.592+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-09T19:21:01.592+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-09T19:21:01.592+0000] {logging_mixin.py:190} INFO - Current task name:insert_data_to_mongodb state:running start_date:2025-03-09 19:21:01.045417+00:00
[2025-03-09T19:21:01.592+0000] {logging_mixin.py:190} INFO - Dag name:a1 and current dag run status:running
[2025-03-09T19:21:01.592+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-09T19:21:01.593+0000] {logging_mixin.py:190} INFO - attampting to insert data to MongoDB....
[2025-03-09T19:21:01.599+0000] {base.py:84} INFO - Retrieving connection 'mongo_default'
[2025-03-09T19:21:02.012+0000] {logging_mixin.py:190} INFO - Document inserted successfully!
[2025-03-09T19:21:02.029+0000] {python.py:240} INFO - Done. Returned value was: {'date': '2025-01-01', 'sentiment_score': 0.8, 'sentiment': 'positive', '_id': ObjectId('67cdea1d6e5f37a400bda10e')}
[2025-03-09T19:21:02.049+0000] {xcom.py:690} ERROR - Object of type ObjectId is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2025-03-09T19:21:02.051+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 92, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 190, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'bson.objectid.ObjectId'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 790, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session_or_null)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3645, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 249, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 688, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 105, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 94, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2025-03-09T19:21:02.063+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-09T19:21:02.065+0000] {logging_mixin.py:190} INFO - Task start:2025-03-09 19:21:01.045417+00:00 end:2025-03-09 19:21:02.063132+00:00 duration:1.017715
[2025-03-09T19:21:02.065+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): insert_data_to_mongodb> dag:<DAG: a1> dagrun:<DagRun a1 @ 2025-03-08 00:00:00+00:00: scheduled__2025-03-08T00:00:00+00:00, state:running, queued_at: 2025-03-09 19:18:39.791379+00:00. externally triggered: False>
[2025-03-09T19:21:02.065+0000] {logging_mixin.py:190} INFO - Failure caused by Object of type ObjectId is not JSON serializable
[2025-03-09T19:21:02.065+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=a1, task_id=insert_data_to_mongodb, run_id=scheduled__2025-03-08T00:00:00+00:00, execution_date=20250308T000000, start_date=20250309T192101, end_date=20250309T192102
[2025-03-09T19:21:02.103+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-09T19:21:02.104+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 49 for task insert_data_to_mongodb (Object of type ObjectId is not JSON serializable; 146)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 92, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 190, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'bson.objectid.ObjectId'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 790, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session_or_null)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3645, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 249, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 688, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 105, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 94, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2025-03-09T19:21:02.154+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-09T19:21:02.190+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-09T19:21:02.191+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
